import '/companion/mygpt-pet.js';
const $=id=>document.getElementById(id);
let snapshot=null, noteId=null, dirty=false, saving=false;
const message=t=>{$('status').textContent=t};
const id=()=>crypto.randomUUID();
const api=async(path,value)=>{const r=await fetch('/desktop-api/'+path,{method:value===undefined?'GET':'POST',headers:{'X-MyGPT-Client':'mygpt-desktop-v1',...(value===undefined?{}:{'Content-Type':'application/json'})},...(value===undefined?{}:{body:JSON.stringify(value)})});let d;try{d=await r.json()}catch{throw Error('服务响应不可读；请保留草稿。')}if(!r.ok)throw Error(d.code||'请求失败');return d};
const download=(name,value)=>{const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
async function commit(value){if(saving)throw Error('正在保存，请稍后再操作。');saving=true;message('正在保存…');try{snapshot=await api('state',{revision:snapshot.revision,value});renderLists();message('已保存到本机。');return true}finally{saving=false}}
function clone(){if(!snapshot)throw Error('本机记录尚未加载。');return structuredClone(snapshot.value)}
function safe(fn){return async()=>{try{await fn()}catch(e){message('操作未完成：'+e.message+'。未覆盖其他窗口的新记录；可导出当前草稿。')}}}
function renderLists(){for(const [section,render] of [['notes',(k,v)=>{const el=document.createElement('div');el.className='item';const span=document.createElement('span');span.textContent=v.title||'未命名笔记';const b=document.createElement('button');b.textContent='打开';b.onclick=()=>{if(saving)return;if(dirty&&!confirm('当前草稿未保存，确定切换？'))return;noteId=k;$('note-title').value=v.title;$('note-body').value=v.body;dirty=false};el.append(span,b);return el}],['sessions',(k,v)=>{const el=document.createElement('div');el.className='item';el.textContent=v.goal+' · '+Math.floor(v.seconds/60)+' 分钟 · '+v.ended_at;return el}]]){const out=$(section);out.replaceChildren();let items=Object.entries(snapshot.value[section]);if(section==='sessions')items.sort((a,b)=>b[1].ended_at.localeCompare(a[1].ended_at));for(const [k,v] of items.slice(0,section==='notes'?1000:30))out.append(render(k,v));if(!items.length)out.textContent='还没有记录。'}tick()}
function tick(){const a=snapshot?.value.active;const elapsed=a?Math.max(0,Math.floor((Date.now()-a.started_ms)/1000)):0;$('timer').textContent=String(Math.floor(elapsed/60)).padStart(2,'0')+':'+String(elapsed%60).padStart(2,'0');$('start').disabled=!snapshot||!!a;$('finish').disabled=!a;}
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{for(const s of document.querySelectorAll('[data-view]'))s.hidden=s.dataset.view!==b.dataset.tab;for(const x of document.querySelectorAll('[data-tab]'))x.setAttribute('aria-selected',String(x===b));};
for(const name of ['note-title','note-body'])$(name).addEventListener('input',()=>{dirty=true});
window.addEventListener('beforeunload',e=>{if(dirty||saving){e.preventDefault();e.returnValue=''}});
$('save-note').onclick=safe(async()=>{const v=clone();const key=noteId||id();v.notes[key]={title:$('note-title').value,body:$('note-body').value};const title=v.notes[key].title,body=v.notes[key].body;await commit(v);noteId=key;dirty=$('note-title').value!==title||$('note-body').value!==body});
$('new-note').onclick=()=>{if(saving)return;if(dirty&&!confirm('当前草稿未保存，确定新建？'))return;noteId=null;$('note-title').value='';$('note-body').value='';dirty=false};
$('save-goal').onclick=safe(async()=>{const v=clone();v.goal=$('goal').value;await commit(v)});
$('start').onclick=safe(async()=>{const minutes=Number($('minutes').value);if(!Number.isInteger(minutes)||minutes<1||minutes>240)throw Error('分钟数应为1–240的整数');const v=clone();v.goal=$('goal').value;v.active={id:id(),goal:v.goal,started_ms:Date.now(),target_sec:minutes*60};await commit(v)});
$('finish').onclick=safe(async()=>{const v=clone(),a=v.active;if(!a)return;v.sessions[a.id]={goal:a.goal,seconds:Math.min(86400,Math.max(0,Math.floor((Date.now()-a.started_ms)/1000))),ended_at:new Date().toISOString()};v.active=null;await commit(v)});
$('export').onclick=safe(async()=>{const latest=await api('state');download('mygpt-workspace-backup.json',{schema:'mygpt-workspace-backup-v1',value:latest.value});message('已导出已保存记录；未保存草稿请另行导出。')});
$('export-draft').onclick=()=>download('mygpt-unsaved-note.json',{schema:'mygpt-workspace-backup-v1',value:{goal:$('goal').value,notes:{[noteId||id()]:{title:$('note-title').value,body:$('note-body').value}},sessions:{},active:null}});
$('import').onchange=safe(async()=>{const file=$('import').files[0];if(!file)return;if(file.size>2*1024*1024+4096)throw Error('备份文件超过限制');if(!confirm('将个人备份合并到本机，冲突笔记保留副本。继续？'))return;snapshot=await api('merge',JSON.parse(await file.text()));$('goal').value=snapshot.value.goal;renderLists();message('备份合并完成。');$('import').value=''});
$('ask').onclick=async()=>{if(!$('consent').checked){$('chat-status').textContent='请先确认本次发送。';return}$('ask').disabled=true;$('chat-status').textContent='正在请求本机模型；不会自动重试…';$('reply').textContent='';try{const r=await api('local-chat',{consent:true,port:Number($('port').value),model:$('model').value,prompt:$('prompt').value});$('reply').textContent=r.reply;$('chat-status').textContent='本机模型回复 · 未独立核验'}catch(e){$('chat-status').textContent=e.message==='local_model_unavailable_no_automatic_retry'?'本机模型未连接、模型未安装或请求超时。请检查本机 Ollama；程序没有自动下载或重试。':e.message}finally{$('ask').disabled=false;$('consent').checked=false}};
setInterval(tick,1000);
(async()=>{try{snapshot=await api('state');$('goal').value=snapshot.value.goal;renderLists();message('本机记录已加载。未发送任何模型请求。')}catch(e){message('读取失败：'+e.message+'。请保留原数据目录。')}})();
