// Generated by python -m mygpt_brain.host_fixtures. Synthetic replay only.
// No live Book/Brain service and no model-generated answer.
export const catalogue = {
  "entries": [
    {
      "brain_receipt": {
        "accepted": true,
        "decision": {
          "action": "explain",
          "model_called": false,
          "policy_version": "quiet-explicit-v1",
          "reason": "explicit_user_request",
          "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:source:original:reader-selected-json-v1:c74e8257ce4288e15ee68dbddd351da42a0fa9c4439b191db5797ea23caea877"
        },
        "disposition": "accepted",
        "event_id": "host-fixture-help"
      },
      "context": {
        "book_id": "demo-book",
        "book_version": "demo_book@0123456789abcdef",
        "captured_at": "2026-09-23T00:00:00Z",
        "course_id": "demo-course",
        "evidence_kind": "SIMULATED",
        "expires_at": "2026-09-23T00:02:00Z",
        "layer_id": "original",
        "mode": "learn",
        "schema_version": "mygpt.reader-context.v2",
        "section_id": "section-1",
        "session_id": "demo-reader-session",
        "source_id": "record-1",
        "source_kind": "paragraph",
        "source_layer": "source",
        "source_serialization": "reader-selected-json-v1",
        "source_sha256": "c74e8257ce4288e15ee68dbddd351da42a0fa9c4439b191db5797ea23caea877"
      },
      "evidence_text": "{\"book_id\":\"demo-book\",\"book_version_id\":\"demo_book@0123456789abcdef\",\"course_id\":\"demo-course\",\"label\":\"ORIGINAL_TRANSCRIPTION_REVIEW_STATUS_NOT_ASSERTED\",\"layer\":\"source\",\"layer_id\":\"original\",\"parent_sources\":[{\"record_id\":\"record-1\",\"source_parts_sha256\":\"055623eae9000a087de5cc7958cd5bf61d7dad6ec0e33c0eef7c47e12eb2f40a\"}],\"parts\":[{\"kind\":\"text\",\"text\":\"两个相同的量相加：\"},{\"display\":true,\"kind\":\"math\",\"latex\":\"x+x=2x\"}],\"portion\":\"body\",\"qualification\":\"\",\"record_id\":\"record-1\",\"schema\":\"reader-selected-json-v1\",\"section_id\":\"section-1\",\"source_kind\":\"paragraph\",\"source_record_ids\":[\"record-1\"],\"title\":\"合成练习 A · 合并同类项\",\"warnings\":[\"DISPLAY_MAY_USE_ANOTHER_LAYER\"]}",
      "fixture_reply": "这是预先编写的演示回复：两个 x 是两份相同的量，因此相加得到 2x。",
      "id": "a-source",
      "label": "练习 A · 原文层",
      "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:source:original:reader-selected-json-v1:c74e8257ce4288e15ee68dbddd351da42a0fa9c4439b191db5797ea23caea877"
    },
    {
      "brain_receipt": {
        "accepted": true,
        "decision": {
          "action": "explain",
          "model_called": false,
          "policy_version": "quiet-explicit-v1",
          "reason": "explicit_user_request",
          "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:correction:correction-1:reader-selected-json-v1:c31b2887cdc75a5e0c0c406940f3fe6e97756ff49626d734d5877743e2400359"
        },
        "disposition": "accepted",
        "event_id": "host-fixture-help"
      },
      "context": {
        "book_id": "demo-book",
        "book_version": "demo_book@0123456789abcdef",
        "captured_at": "2026-09-23T00:00:00Z",
        "course_id": "demo-course",
        "evidence_kind": "SIMULATED",
        "expires_at": "2026-09-23T00:02:00Z",
        "layer_id": "correction-1",
        "mode": "learn",
        "schema_version": "mygpt.reader-context.v2",
        "section_id": "section-1",
        "session_id": "demo-reader-session",
        "source_id": "record-1",
        "source_kind": "paragraph",
        "source_layer": "correction",
        "source_serialization": "reader-selected-json-v1",
        "source_sha256": "c31b2887cdc75a5e0c0c406940f3fe6e97756ff49626d734d5877743e2400359"
      },
      "evidence_text": "{\"book_id\":\"demo-book\",\"book_version_id\":\"demo_book@0123456789abcdef\",\"course_id\":\"demo-course\",\"label\":\"AI_CORRECTION_NOT_OFFICIAL_ERRATUM\",\"layer\":\"correction\",\"layer_id\":\"correction-1\",\"parent_sources\":[{\"record_id\":\"record-1\",\"source_parts_sha256\":\"055623eae9000a087de5cc7958cd5bf61d7dad6ec0e33c0eef7c47e12eb2f40a\"}],\"parts\":[{\"kind\":\"text\",\"text\":\"把系数相加，字母部分保持不变。\"},{\"display\":true,\"kind\":\"math\",\"latex\":\"(1+1)x=2x\"}],\"portion\":\"body\",\"qualification\":\"\",\"record_id\":\"record-1\",\"schema\":\"reader-selected-json-v1\",\"section_id\":\"section-1\",\"source_kind\":\"paragraph\",\"source_record_ids\":[\"record-1\"],\"title\":\"合成练习 A · 合并同类项\",\"warnings\":[\"SOURCE_BINDING_IS_NOT_MATHEMATICAL_ACCEPTANCE\"]}",
      "fixture_reply": "这是预先编写的演示回复：当前选择的是合成校正层。系数 1 与 1 相加得到 2，字母部分 x 不变；这不是官方勘误。",
      "id": "a-correction",
      "label": "练习 A · 校正层",
      "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:correction:correction-1:reader-selected-json-v1:c31b2887cdc75a5e0c0c406940f3fe6e97756ff49626d734d5877743e2400359"
    },
    {
      "brain_receipt": {
        "accepted": true,
        "decision": {
          "action": "explain",
          "model_called": false,
          "policy_version": "quiet-explicit-v1",
          "reason": "explicit_user_request",
          "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:derived:group-1-hint:reader-selected-json-v1:cb4fdf1c0180e8ec1f5af98b6ab07e369a715e54ced71803a3af646749e8b507"
        },
        "disposition": "accepted",
        "event_id": "host-fixture-help"
      },
      "context": {
        "book_id": "demo-book",
        "book_version": "demo_book@0123456789abcdef",
        "captured_at": "2026-09-23T00:00:00Z",
        "course_id": "demo-course",
        "evidence_kind": "SIMULATED",
        "expires_at": "2026-09-23T00:02:00Z",
        "layer_id": "group-1-hint",
        "mode": "learn",
        "schema_version": "mygpt.reader-context.v2",
        "section_id": "section-1",
        "session_id": "demo-reader-session",
        "source_id": "record-1",
        "source_kind": "paragraph",
        "source_layer": "derived",
        "source_serialization": "reader-selected-json-v1",
        "source_sha256": "cb4fdf1c0180e8ec1f5af98b6ab07e369a715e54ced71803a3af646749e8b507"
      },
      "evidence_text": "{\"book_id\":\"demo-book\",\"book_version_id\":\"demo_book@0123456789abcdef\",\"course_id\":\"demo-course\",\"label\":\"AI_DERIVED_NOT_TEXTBOOK_STANDARD_ANSWER\",\"layer\":\"derived\",\"layer_id\":\"group-1-hint\",\"parent_sources\":[{\"record_id\":\"record-1\",\"source_parts_sha256\":\"055623eae9000a087de5cc7958cd5bf61d7dad6ec0e33c0eef7c47e12eb2f40a\"}],\"parts\":[{\"kind\":\"text\",\"text\":\"把两个 x 看作两份相同的量。\"}],\"portion\":\"hint\",\"qualification\":\"人为编写的合成演示，非教材标准答案。\",\"record_id\":\"record-1\",\"schema\":\"reader-selected-json-v1\",\"section_id\":\"section-1\",\"source_kind\":\"paragraph\",\"source_record_ids\":[\"record-1\"],\"title\":\"合成练习 A · 思考提示与推导\",\"warnings\":[]}",
      "fixture_reply": "这是预先编写的演示回复：先想象两份相同的量。此处只回放提示，不自动展开解答。",
      "id": "a-hint",
      "label": "练习 A · 推导提示",
      "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:derived:group-1-hint:reader-selected-json-v1:cb4fdf1c0180e8ec1f5af98b6ab07e369a715e54ced71803a3af646749e8b507"
    },
    {
      "brain_receipt": {
        "accepted": true,
        "decision": {
          "action": "explain",
          "model_called": false,
          "policy_version": "quiet-explicit-v1",
          "reason": "explicit_user_request",
          "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:derived:group-1-solution:reader-selected-json-v1:f35c5596fac872559f37c9c1e121cff6235156d2fa69e20692d58033f7cca329"
        },
        "disposition": "accepted",
        "event_id": "host-fixture-help"
      },
      "context": {
        "book_id": "demo-book",
        "book_version": "demo_book@0123456789abcdef",
        "captured_at": "2026-09-23T00:00:00Z",
        "course_id": "demo-course",
        "evidence_kind": "SIMULATED",
        "expires_at": "2026-09-23T00:02:00Z",
        "layer_id": "group-1-solution",
        "mode": "learn",
        "schema_version": "mygpt.reader-context.v2",
        "section_id": "section-1",
        "session_id": "demo-reader-session",
        "source_id": "record-1",
        "source_kind": "paragraph",
        "source_layer": "derived",
        "source_serialization": "reader-selected-json-v1",
        "source_sha256": "f35c5596fac872559f37c9c1e121cff6235156d2fa69e20692d58033f7cca329"
      },
      "evidence_text": "{\"book_id\":\"demo-book\",\"book_version_id\":\"demo_book@0123456789abcdef\",\"course_id\":\"demo-course\",\"label\":\"AI_DERIVED_NOT_TEXTBOOK_STANDARD_ANSWER\",\"layer\":\"derived\",\"layer_id\":\"group-1-solution\",\"parent_sources\":[{\"record_id\":\"record-1\",\"source_parts_sha256\":\"055623eae9000a087de5cc7958cd5bf61d7dad6ec0e33c0eef7c47e12eb2f40a\"}],\"parts\":[{\"display\":true,\"kind\":\"math\",\"latex\":\"x+x=(1+1)x=2x\"}],\"portion\":\"solution\",\"qualification\":\"人为编写的合成演示，非教材标准答案。\",\"record_id\":\"record-1\",\"schema\":\"reader-selected-json-v1\",\"section_id\":\"section-1\",\"source_kind\":\"paragraph\",\"source_record_ids\":[\"record-1\"],\"title\":\"合成练习 A · 思考提示与推导\",\"warnings\":[]}",
      "fixture_reply": "这是预先编写的演示回复：把公共的 x 提出来，得到 (1+1)x，再合并系数为 2x。此内容不是教材标准答案。",
      "id": "a-solution",
      "label": "练习 A · 推导解答",
      "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-1:derived:group-1-solution:reader-selected-json-v1:f35c5596fac872559f37c9c1e121cff6235156d2fa69e20692d58033f7cca329"
    },
    {
      "brain_receipt": {
        "accepted": true,
        "decision": {
          "action": "explain",
          "model_called": false,
          "policy_version": "quiet-explicit-v1",
          "reason": "explicit_user_request",
          "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-2:source:original:reader-selected-json-v1:94618c0ce0da7fe8d2a1903dadae7271425b0c46ecd77058b96c02a8d8ce2e7c"
        },
        "disposition": "accepted",
        "event_id": "host-fixture-help"
      },
      "context": {
        "book_id": "demo-book",
        "book_version": "demo_book@0123456789abcdef",
        "captured_at": "2026-09-23T00:00:00Z",
        "course_id": "demo-course",
        "evidence_kind": "SIMULATED",
        "expires_at": "2026-09-23T00:02:00Z",
        "layer_id": "original",
        "mode": "learn",
        "schema_version": "mygpt.reader-context.v2",
        "section_id": "section-1",
        "session_id": "demo-reader-session",
        "source_id": "record-2",
        "source_kind": "paragraph",
        "source_layer": "source",
        "source_serialization": "reader-selected-json-v1",
        "source_sha256": "94618c0ce0da7fe8d2a1903dadae7271425b0c46ecd77058b96c02a8d8ce2e7c"
      },
      "evidence_text": "{\"book_id\":\"demo-book\",\"book_version_id\":\"demo_book@0123456789abcdef\",\"course_id\":\"demo-course\",\"label\":\"ORIGINAL_TRANSCRIPTION_REVIEW_STATUS_NOT_ASSERTED\",\"layer\":\"source\",\"layer_id\":\"original\",\"parent_sources\":[{\"record_id\":\"record-2\",\"source_parts_sha256\":\"b960dee022827715a2c9d5e13c6a76b3ef9a2b82d5292a29616453186c281cad\"}],\"parts\":[{\"kind\":\"text\",\"text\":\"平方与分别平方后相加不相同：\"},{\"display\":true,\"kind\":\"math\",\"latex\":\"(x+1)^2=x^2+2x+1\"}],\"portion\":\"body\",\"qualification\":\"\",\"record_id\":\"record-2\",\"schema\":\"reader-selected-json-v1\",\"section_id\":\"section-1\",\"source_kind\":\"paragraph\",\"source_record_ids\":[\"record-2\"],\"title\":\"合成练习 B · 平方展开\",\"warnings\":[]}",
      "fixture_reply": "这是预先编写的演示回复：(x+1)(x+1) 展开包含两项 x，因此中间项是 2x，不能漏掉。",
      "id": "b-source",
      "label": "练习 B · 原文层",
      "source_ref": "reader:v2:demo-course:demo-book:demo_book%400123456789abcdef:section-1:paragraph:record-2:source:original:reader-selected-json-v1:94618c0ce0da7fe8d2a1903dadae7271425b0c46ecd77058b96c02a8d8ce2e7c"
    }
  ],
  "fixture_time": "2026-09-23T00:00:00+00:00",
  "live_book_connected": false,
  "model_calls": 0,
  "schema": "mygpt.host-replay.v1",
  "scope": "SYNTHETIC_FIXED_REPLAY",
  "verified_modes": [
    "preview",
    "learn",
    "review",
    "practice"
  ]
};
